trigger:
- main

pool:
  name: diksha_pool

steps:
# Checkout the code
- checkout: self
  clean: true

# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Install dependencies and build the app
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Archive the build output (dist folder for Vite apps)
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'   # <---- changed build -> dist
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/dist.zip'     # <---- changed filename
    replaceExistingArchive: true
  displayName: 'Archive dist folder'

# Publish the ZIP as an artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish artifact'

# Deploy the ZIP to Azure Web App
- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'demo-diksha'
    resourceGroupName: 'DikshaRG'
    appName: 'youtubeapp'
    package: '$(Build.ArtifactStagingDirectory)/dist.zip'        # <---- updated path
    appType: 'webAppLinux'
    runtimeStack: 'NODE|20-lts'
    deploymentMethod: 'auto'
