trigger:
- main

pool:
  name: diksha_pool

steps:
# Clean checkout to avoid auth issues and start fresh
- checkout: self
  persistCredentials: false
  clean: true

# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Install dependencies and build
- script: |
    npm ci
    npm run build
  displayName: 'Install dependencies and build'

# Debug: List build folder
- script: |
    echo "Build folder contents:"
    ls -la build
  displayName: 'Debug: List build folder'

# Copy build output to artifact staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/build'
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to staging directory'

# Debug: List artifact staging directory
- script: |
    echo "Staging directory contents:"
    ls -la $(Build.ArtifactStagingDirectory)
  displayName: 'Debug: List staging folder'

# Publish the artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'

# Deploy to Azure Web App
- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'demo-diksha'
    resourceGroupName: 'DikshaRG'
    appName: 'demo--app'
    package: '$(Build.ArtifactStagingDirectory)' 
    appType: 'webAppLinux'
    runtimeStack: 'NODE|20-lts'
    deploymentMethod: 'auto'
