trigger:
- main

pool:
  name: diksha_pool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Copy build output to artifact staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/build'  # or dist, adjust based on your project
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to staging directory'

# Publish the artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'demo-diksha'
    resourceGroupName: 'DikshaRG'
    appName: 'demo--app'
    package: '$(System.DefaultWorkingDirectory)/drop'
    appType: 'webAppLinux'           # required for Linux Web Apps
    runtimeStack: 'NODE|20-lts'
    deploymentMethod: 'auto'