trigger:
- main

pool:
  name: diksha_pool

steps:
# Use clean checkout to avoid Git auth issues on public repo
- checkout: self
  persistCredentials: false
  clean: true

# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Install dependencies and build project
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Copy build output to artifact staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/build'  # Change to /dist if that's your build folder
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to staging directory'

# Publish the artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'

# Deploy to Azure Web App
- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'demo-diksha'
    resourceGroupName: 'DikshaRG'
    appName: 'demo--app'
    package: '$(Build.ArtifactStagingDirectory)'
    appType: 'webAppLinux'
    runtimeStack: 'NODE|20-lts'
    deploymentMethod: 'auto'
