trigger:
- main

pool:
  name: diksha_pool  # Self-hosted agent

variables:
  buildDir: '$(System.DefaultWorkingDirectory)/build'
  artifactName: 'drop'
  # zipPath: '$(Build.ArtifactStagingDirectory)/build.zip'

steps:
# Checkout code
- checkout: self
  clean: true

# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Add staticwebapp.config.json for React Router support
#- script: |
#    echo ^{
#    echo   "navigationFallback": {
#    echo     "rewrite": "/index.html",
#    echo     "exclude": ["/static/*"]
#    echo   }
#    echo ^} > public/staticwebapp.config.json
#  displayName: 'Create staticwebapp.config.json'

# Install dependencies and build the React app
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Archive the build output
# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(buildDir)'
#     includeRootFolder: false
#     archiveType: 'zip'
#     archiveFile: '$(zipPath)'
#     replaceExistingArchive: true
#   displayName: 'Archive React build folder'

# Publish the ZIP as an artifact
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(zipPath)'
#     ArtifactName: '$(artifactName)'
#     publishLocation: 'Container'
#   displayName: 'Publish artifact'

# Deploy the ZIP to Azure Web App
# - task: AzureWebApp@1
#   displayName: 'Deploy to Azure Web App'
#   inputs:
#     azureSubscription: 'demo-diksha'
#     appName: 'youtubeapp'
#     package: '$(zipPath)'
#     appType: 'webAppLinux'
#     runtimeStack: 'NODE|20-lts'
#     deploymentMethod: 'zipDeploy'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    output_location: 'build'
    azure_static_web_apps_api_token: 'c371475d8f7fc13bfb326963c4fb72bf5588ef512923e48d5fc5e0f17820d45806-86eb74c9-8e59-4be8-b265-2200e9456af600019100c1385c00'