trigger:
- main

pool:
  name: diksha_pool

steps:
# Clean checkout to avoid auth issues and start fresh
- checkout: self
  persistCredentials: false
  clean: true

# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Install dependencies and build
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Show contents of build folder (for debugging)
- script: |
    echo "Build folder contents:"
    ls -la $(System.DefaultWorkingDirectory)/build
  displayName: 'Debug: List build folder'

# Copy build output to artifact staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/build'
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/drop'
  displayName: 'Copy files to staging directory'

# Show contents of staging directory (for debugging)
- script: |
    echo "Staging directory contents:"
    ls -la $(Build.ArtifactStagingDirectory)/drop
  displayName: 'Debug: List staging folder'

# Archive the files into a .zip (required for deployment)
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/drop'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'
    replaceExistingArchive: true
  displayName: 'Archive build output'

# Publish the artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'

# Deploy to Azure Web App using the zip file
- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'demo-diksha'
    resourceGroupName: 'DikshaRG'
    appName: 'demo--app'
    package: '$(Build.ArtifactStagingDirectory)/drop.zip'
    appType: 'webAppLinux'
    runtimeStack: 'NODE|20-lts'
    deploymentMethod: 'auto'
